title: Avrha-Blog
description: "A Hacker's Journey exploring Computers"
author:
  name: "avrha"
  email: "sjferenchak@gmail.com"
  url: "https://avrha.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "avrha"
year : "2021"
